#if !canImport(ObjectiveC)
import XCTest

extension ElementContentPartTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ElementContentPartTests = [
        ("testAppendingContentOfSequence", testAppendingContentOfSequence),
        ("testAppendingObject", testAppendingObject),
        ("testAppendingObjects", testAppendingObjects),
        ("testAppendingString", testAppendingString),
        ("testCompression", testCompression),
        ("testExpressibleByStringLiteral", testExpressibleByStringLiteral),
        ("testInternalHelpers", testInternalHelpers),
    ]
}

extension ElementContent_LookupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ElementContent_LookupTests = [
        ("testFindingFirstObjectRecursive", testFindingFirstObjectRecursive),
        ("testFindingFirstObjectShallow", testFindingFirstObjectShallow),
        ("testFindingLastObjectRecursive", testFindingLastObjectRecursive),
        ("testFindingLastObjectShallow", testFindingLastObjectShallow),
        ("testFindingObjectsRecursive", testFindingObjectsRecursive),
        ("testFindingObjectsShallow", testFindingObjectsShallow),
    ]
}

extension ElementProtocolsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ElementProtocolsTests = [
        ("testConvenienceImplementations", testConvenienceImplementations),
    ]
}

extension ElementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ElementTests = [
        ("testAppendingContentOfSequence", testAppendingContentOfSequence),
        ("testAppendingObject", testAppendingObject),
        ("testAppendingObjects", testAppendingObjects),
        ("testAppendingString", testAppendingString),
    ]
}

extension Element_LookupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Element_LookupTests = [
        ("testConverting", testConverting),
        ("testExistingAttributeConversion", testExistingAttributeConversion),
        ("testExistingAttributeLookup", testExistingAttributeLookup),
        ("testExistingElementLookupAtPath", testExistingElementLookupAtPath),
        ("testExistingElementLookupAtVariadicPath", testExistingElementLookupAtVariadicPath),
        ("testExistingElementsLookup", testExistingElementsLookup),
        ("testExistingStringContentConversion", testExistingStringContentConversion),
        ("testExistingStringContentLookup", testExistingStringContentLookup),
        ("testFailedExistingAttributeConversion", testFailedExistingAttributeConversion),
        ("testFailedExistingStringContentConversion", testFailedExistingStringContentConversion),
        ("testFailedRawRepresentableAttributeConversion", testFailedRawRepresentableAttributeConversion),
        ("testFailedRawRepresentableExistingStringContentConversion", testFailedRawRepresentableExistingStringContentConversion),
        ("testLosslessStringConvertibleAttributeConversion", testLosslessStringConvertibleAttributeConversion),
        ("testLosslessStringConvertibleStringContentConversion", testLosslessStringConvertibleStringContentConversion),
        ("testNonExistingAttributeConversion", testNonExistingAttributeConversion),
        ("testNonExistingAttributeLookup", testNonExistingAttributeLookup),
        ("testNonExistingElementLookupAtPath", testNonExistingElementLookupAtPath),
        ("testNonExistingElementLookupAtVariadicPath", testNonExistingElementLookupAtVariadicPath),
        ("testNonExistingElementsLookup", testNonExistingElementsLookup),
        ("testNonExistingStringContentConversion", testNonExistingStringContentConversion),
        ("testNonExistingStringContentLookup", testNonExistingStringContentLookup),
        ("testRawRepresentableAttributeConversion", testRawRepresentableAttributeConversion),
        ("testRawRepresentableLosslessStringConvertibleAttributeConversion", testRawRepresentableLosslessStringConvertibleAttributeConversion),
        ("testRawRepresentableLosslessStringConvertibleStringContentConversion", testRawRepresentableLosslessStringConvertibleStringContentConversion),
        ("testRawRepresentableStringContentConversion", testRawRepresentableStringContentConversion),
    ]
}

extension Element_MutationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Element_MutationTests = [
        ("testMutatingAccessToElementAtInvalidPathThrows", testMutatingAccessToElementAtInvalidPathThrows),
        ("testMutatingAccessToElementAtPath", testMutatingAccessToElementAtPath),
        ("testMutatingAccessToElementAtVariadicPath", testMutatingAccessToElementAtVariadicPath),
        ("testRemovingElementAtEmptyPath", testRemovingElementAtEmptyPath),
        ("testRemovingElementAtPath", testRemovingElementAtPath),
        ("testRemovingElementAtVariadicPath", testRemovingElementAtVariadicPath),
        ("testRemovingInexistentElementAtPath", testRemovingInexistentElementAtPath),
        ("testReplacingElementAtPath", testReplacingElementAtPath),
        ("testReplacingElementAtVariadicPath", testReplacingElementAtVariadicPath),
    ]
}

extension ErrorsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrorsTests = [
        ("testLookupErrorDescription", testLookupErrorDescription),
        ("testParserMissingObjectError", testParserMissingObjectError),
        ("testParserUnknownError", testParserUnknownError),
    ]
}

extension GitHubIssueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GitHubIssueTests = [
        ("testIssue11", testIssue11),
    ]
}

extension ParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserTests = [
        ("testMixedContentParsing", testMixedContentParsing),
        ("testParsingAndConverting", testParsingAndConverting),
        ("testParsingError", testParsingError),
        ("testRepetitiveParsing", testRepetitiveParsing),
        ("testSuccessfulParsing", testSuccessfulParsing),
    ]
}

extension SerializationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SerializationTests = [
        ("testConvertibleSerialization", testConvertibleSerialization),
        ("testDocumentEncodingDescription", testDocumentEncodingDescription),
        ("testEscapableContentDescription", testEscapableContentDescription),
        ("testEscapableContentQuotesDescription", testEscapableContentQuotesDescription),
        ("testEscapingStrings", testEscapingStrings),
        ("testMixedContentSerialization", testMixedContentSerialization),
        ("testXMLDocumentSerialization", testXMLDocumentSerialization),
        ("testXMLSerialization", testXMLSerialization),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ElementContentPartTests.__allTests__ElementContentPartTests),
        testCase(ElementContent_LookupTests.__allTests__ElementContent_LookupTests),
        testCase(ElementProtocolsTests.__allTests__ElementProtocolsTests),
        testCase(ElementTests.__allTests__ElementTests),
        testCase(Element_LookupTests.__allTests__Element_LookupTests),
        testCase(Element_MutationTests.__allTests__Element_MutationTests),
        testCase(ErrorsTests.__allTests__ErrorsTests),
        testCase(GitHubIssueTests.__allTests__GitHubIssueTests),
        testCase(ParserTests.__allTests__ParserTests),
        testCase(SerializationTests.__allTests__SerializationTests),
    ]
}
#endif
