#if !canImport(ObjectiveC)
import XCTest

extension ElementContentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ElementContentTests = [
        ("testAppendingContentOfSequence", testAppendingContentOfSequence),
        ("testAppendingObject", testAppendingObject),
        ("testAppendingObjects", testAppendingObjects),
        ("testAppendingString", testAppendingString),
        ("testCompression", testCompression),
        ("testExpressibleByStringLiteral", testExpressibleByStringLiteral),
        ("testInternalHelpers", testInternalHelpers),
    ]
}

extension ElementContent_DeprecatedTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ElementContent_DeprecatedTests = [
        ("testElementContentAppend", testElementContentAppend),
        ("testElementContentConverted", testElementContentConverted),
        ("testElementRemoveAtPath", testElementRemoveAtPath),
        ("testElementRemoveAtVariadicPath", testElementRemoveAtVariadicPath),
    ]
}

extension ElementContent_LookupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ElementContent_LookupTests = [
        ("testFindingFirstObjectRecursive", testFindingFirstObjectRecursive),
        ("testFindingFirstObjectShallow", testFindingFirstObjectShallow),
        ("testFindingLastObjectRecursive", testFindingLastObjectRecursive),
        ("testFindingLastObjectShallow", testFindingLastObjectShallow),
        ("testFindingObjectsRecursive", testFindingObjectsRecursive),
        ("testFindingObjectsShallow", testFindingObjectsShallow),
    ]
}

extension ElementTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ElementTests = [
        ("testAppendingContentOfSequence", testAppendingContentOfSequence),
        ("testAppendingObject", testAppendingObject),
        ("testAppendingObjects", testAppendingObjects),
        ("testAppendingString", testAppendingString),
        ("testExpressibleByStringLiteral", testExpressibleByStringLiteral),
    ]
}

extension Element_LookupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Element_LookupTests = [
        ("testExistingAttributeConversion", testExistingAttributeConversion),
        ("testExistingAttributeConversionAtPath", testExistingAttributeConversionAtPath),
        ("testExistingAttributeConversionAtVariadicPath", testExistingAttributeConversionAtVariadicPath),
        ("testExistingAttributeLookup", testExistingAttributeLookup),
        ("testExistingAttributeLookupAtPath", testExistingAttributeLookupAtPath),
        ("testExistingAttributeLookupAtVariadicPath", testExistingAttributeLookupAtVariadicPath),
        ("testExistingElementLookupAtPath", testExistingElementLookupAtPath),
        ("testExistingElementLookupAtVariadicPath", testExistingElementLookupAtVariadicPath),
        ("testExistingElementsLookup", testExistingElementsLookup),
        ("testExistingElementsLookupAtPath", testExistingElementsLookupAtPath),
        ("testExistingElementsLookupAtVariadicPath", testExistingElementsLookupAtVariadicPath),
        ("testExistingStringContentConversion", testExistingStringContentConversion),
        ("testExistingStringContentConversionAtPath", testExistingStringContentConversionAtPath),
        ("testExistingStringContentConversionAtVariadicPath", testExistingStringContentConversionAtVariadicPath),
        ("testExistingStringContentLookup", testExistingStringContentLookup),
        ("testExistingStringContentLookupAtPath", testExistingStringContentLookupAtPath),
        ("testExistingStringContentLookupAtVariadicPath", testExistingStringContentLookupAtVariadicPath),
        ("testFailedExistingAttributeConversion", testFailedExistingAttributeConversion),
        ("testFailedExistingAttributeConversionAtPath", testFailedExistingAttributeConversionAtPath),
        ("testFailedExistingAttributeConversionAtVariadicPath", testFailedExistingAttributeConversionAtVariadicPath),
        ("testFailedExistingStringContentConversion", testFailedExistingStringContentConversion),
        ("testFailedExistingStringContentConversionAtPath", testFailedExistingStringContentConversionAtPath),
        ("testFailedExistingStringContentConversionAtVariadicPath", testFailedExistingStringContentConversionAtVariadicPath),
        ("testFailedRawRepresentableAttributeConversion", testFailedRawRepresentableAttributeConversion),
        ("testFailedRawRepresentableExistingStringContentConversion", testFailedRawRepresentableExistingStringContentConversion),
        ("testLosslessStringConvertibleAttributeConversion", testLosslessStringConvertibleAttributeConversion),
        ("testLosslessStringConvertibleAttributeConversionAtPath", testLosslessStringConvertibleAttributeConversionAtPath),
        ("testLosslessStringConvertibleAttributeConversionAtVariadicPath", testLosslessStringConvertibleAttributeConversionAtVariadicPath),
        ("testLosslessStringConvertibleStringContentConversion", testLosslessStringConvertibleStringContentConversion),
        ("testLosslessStringConvertibleStringContentConversionAtPath", testLosslessStringConvertibleStringContentConversionAtPath),
        ("testLosslessStringConvertibleStringContentConversionAtVariadicPath", testLosslessStringConvertibleStringContentConversionAtVariadicPath),
        ("testNonExistingAttributeConversion", testNonExistingAttributeConversion),
        ("testNonExistingAttributeConversionAtPath", testNonExistingAttributeConversionAtPath),
        ("testNonExistingAttributeConversionAtVariadicPath", testNonExistingAttributeConversionAtVariadicPath),
        ("testNonExistingAttributeLookup", testNonExistingAttributeLookup),
        ("testNonExistingAttributeLookupAtPath", testNonExistingAttributeLookupAtPath),
        ("testNonExistingAttributeLookupAtVariadicPath", testNonExistingAttributeLookupAtVariadicPath),
        ("testNonExistingElementLookupAtPath", testNonExistingElementLookupAtPath),
        ("testNonExistingElementLookupAtVariadicPath", testNonExistingElementLookupAtVariadicPath),
        ("testNonExistingElementsLookup", testNonExistingElementsLookup),
        ("testNonExistingElementsLookupAtPath", testNonExistingElementsLookupAtPath),
        ("testNonExistingElementsLookupAtVariadicPath", testNonExistingElementsLookupAtVariadicPath),
        ("testNonExistingStringContentConversion", testNonExistingStringContentConversion),
        ("testNonExistingStringContentConversionAtPath", testNonExistingStringContentConversionAtPath),
        ("testNonExistingStringContentConversionAtVariadicPath", testNonExistingStringContentConversionAtVariadicPath),
        ("testNonExistingStringContentLookup", testNonExistingStringContentLookup),
        ("testNonExistingStringContentLookupAtPath", testNonExistingStringContentLookupAtPath),
        ("testNonExistingStringContentLookupAtVariadicPath", testNonExistingStringContentLookupAtVariadicPath),
        ("testRawRepresentableAttributeConversion", testRawRepresentableAttributeConversion),
        ("testRawRepresentableAttributeConversionAtPath", testRawRepresentableAttributeConversionAtPath),
        ("testRawRepresentableAttributeConversionAtVariadicPath", testRawRepresentableAttributeConversionAtVariadicPath),
        ("testRawRepresentableLosslessStringConvertibleAttributeConversion", testRawRepresentableLosslessStringConvertibleAttributeConversion),
        ("testRawRepresentableLosslessStringConvertibleAttributeConversionAtPath", testRawRepresentableLosslessStringConvertibleAttributeConversionAtPath),
        ("testRawRepresentableLosslessStringConvertibleAttributeConversionAtVariadicPath", testRawRepresentableLosslessStringConvertibleAttributeConversionAtVariadicPath),
        ("testRawRepresentableLosslessStringConvertibleStringContentConversion", testRawRepresentableLosslessStringConvertibleStringContentConversion),
        ("testRawRepresentableLosslessStringConvertibleStringContentConversionAtPath", testRawRepresentableLosslessStringConvertibleStringContentConversionAtPath),
        ("testRawRepresentableLosslessStringConvertibleStringContentConversionAtVariadicPath", testRawRepresentableLosslessStringConvertibleStringContentConversionAtVariadicPath),
        ("testRawRepresentableStringContentConversion", testRawRepresentableStringContentConversion),
        ("testRawRepresentableStringContentConversionAtPath", testRawRepresentableStringContentConversionAtPath),
        ("testRawRepresentableStringContentConversionAtVariadicPath", testRawRepresentableStringContentConversionAtVariadicPath),
    ]
}

extension Element_MutationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Element_MutationTests = [
        ("testMutatingAccessToElementAtInvalidPathThrows", testMutatingAccessToElementAtInvalidPathThrows),
        ("testMutatingAccessToElementAtPath", testMutatingAccessToElementAtPath),
        ("testMutatingAccessToElementAtVariadicPath", testMutatingAccessToElementAtVariadicPath),
        ("testRemovingElementAtEmptyPath", testRemovingElementAtEmptyPath),
        ("testRemovingElementAtPath", testRemovingElementAtPath),
        ("testRemovingElementAtVariadicPath", testRemovingElementAtVariadicPath),
        ("testRemovingInexistentElementAtPath", testRemovingInexistentElementAtPath),
        ("testReplacingElementAtPath", testReplacingElementAtPath),
        ("testReplacingElementAtVariadicPath", testReplacingElementAtVariadicPath),
    ]
}

extension ErrorsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrorsTests = [
        ("testLookupErrorDescription", testLookupErrorDescription),
        ("testParserMissingObjectError", testParserMissingObjectError),
        ("testParserUnknownError", testParserUnknownError),
    ]
}

extension GitHubIssueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GitHubIssueTests = [
        ("testIssue11", testIssue11),
    ]
}

extension ParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserTests = [
        ("testMixedContentParsing", testMixedContentParsing),
        ("testParsingError", testParsingError),
        ("testRepetitiveParsing", testRepetitiveParsing),
        ("testSuccessfulParsing", testSuccessfulParsing),
    ]
}

extension SerializationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SerializationTests = [
        ("testDocumentEncodingDescription", testDocumentEncodingDescription),
        ("testEscapableContentDescription", testEscapableContentDescription),
        ("testEscapableContentQuotesDescription", testEscapableContentQuotesDescription),
        ("testEscapingStrings", testEscapingStrings),
        ("testMixedContentSerialization", testMixedContentSerialization),
        ("testXMLDocumentSerialization", testXMLDocumentSerialization),
        ("testXMLSerialization", testXMLSerialization),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ElementContentTests.__allTests__ElementContentTests),
        testCase(ElementContent_DeprecatedTests.__allTests__ElementContent_DeprecatedTests),
        testCase(ElementContent_LookupTests.__allTests__ElementContent_LookupTests),
        testCase(ElementTests.__allTests__ElementTests),
        testCase(Element_LookupTests.__allTests__Element_LookupTests),
        testCase(Element_MutationTests.__allTests__Element_MutationTests),
        testCase(ErrorsTests.__allTests__ErrorsTests),
        testCase(GitHubIssueTests.__allTests__GitHubIssueTests),
        testCase(ParserTests.__allTests__ParserTests),
        testCase(SerializationTests.__allTests__SerializationTests),
    ]
}
#endif
